# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Deeply Learning
tagline:          'Vrishank Bhardwaj'
description:      'Vrishank Bhardwaj'
url:              http://vrishank.me
baseurl:          /

paginate:         5

# Custom vars
version:          2.1.0
